b2bmart/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('help/', TemplateView.as_view(template_name="help.html"), name="help"),

    path('about-us/', TemplateView.as_view(template_name="company/about-us.html"), name="about_us"),
    path('about-management/', TemplateView.as_view(template_name="company/management.html"), name="about_management"),
    path('about-media-center/', TemplateView.as_view(template_name="company/media-center.html"), name="about_media_center"),
    path('about-work-with-us/', TemplateView.as_view(template_name="company/workWithUs.html"), name="about_work_with_us"),
    path('about-contact-us/', TemplateView.as_view(template_name="company/contact-us.html"), name="about_contact_us"),
    path('help-center/', TemplateView.as_view(template_name="company/help.html"), name="help_center"),
    path('privacy-policy/', TemplateView.as_view(template_name="company/privacy-policy.html"), name="privacy_policy"),
    path('trading-policy/', TemplateView.as_view(template_name="company/trading-policy.html"), name="trading_policy"),
    path('term-condition/', TemplateView.as_view(template_name="company/term-condition.html"), name="term_condition"),
    path('edit-profile/', TemplateView.as_view(template_name="company/seller/user.html.html"), name="edit_profile"),
    path('certificate/', TemplateView.as_view(template_name="company/certificate.html"), name="certificate"),
    path('media-center/', TemplateView.as_view(template_name="company/media-center.html"), name="media_center"),
    path('advertise/', TemplateView.as_view(template_name="company/advertise.html"), name="advertise"),

    path('order-track/', TemplateView.as_view(template_name="company/ordertrack.html"), name="order_track"),
    #path('cart/', TemplateView.as_view(template_name="company/cart.html"), name="cart"),

    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('accounts/', include('allauth.urls')),
    path('', include("product.urls", namespace="product")),
    path('dashboard/', include('dashboard.urls', namespace="dashboard")),

    

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dashboard/urls.py
from django.urls import path
from . import views
app_name = "dashboard"

urlpatterns = [
    path('seller-dashboard/',views.SellerDashboardView.as_view(), name="seller_dashboard"),
    path('seller/contact-profile/',views.SellerContactProfileView.as_view(), name="seller_contact_profile"),
    path('seller/business-profile/',views.SellerBusinessProfileView, name="seller_business_profile"),
    path('seller/statutory/',views.SellerStatutoryView.as_view(), name="seller_statutory"),
    path('seller/bank/',views.SellerBankView.as_view(), name="seller_bank"),
    
    
    
    path('seller/add-product/',views.SellerAddProductView.as_view(), name="seller_add_product"),
    path('seller/manage-product/',views.SellerManageProductView, name="seller_manage_product"),
    path('seller/rearrange-product/',views.SellerReArrangeProductView.as_view(), name="seller_rearrange_product"),
    path('seller/bulk-price-update/<str:pk>',views.SellerBulkPriceUpdateView, name="seller_bulk_price_update"),
    path('seller/single-product-update/<str:pk>', views.SellerSingleProductUpdateView, name="seller_single_product_update"),
    path('<int:pk>/delete_product/', views.sellerDeleteProduct, name="seller_delete_product"),
    path('seller/category-report/',views.SellerCategoryReportView.as_view(), name="seller_category_report"),
    path('seller/analytics/',views.SellerAnalyticView.as_view(), name="seller_analytics"),
    

    path('seller/business-outlook/',views.SellerBusinessOutlookView.as_view(), name="seller_business_outlook"),
    path('seller/finance/',views.SellerFinancecView.as_view(), name="seller_finance"),
    path('seller/history/',views.SellerHistoryView.as_view(), name="seller_history"),
    path('seller/document/',views.SellerPhotoDocumentView.as_view(), name="seller_document"),
    path('seller/membership/',views.SellerMembershipView.as_view(), name="seller_membership"),
    path('seller/my-enquiry/',views.SellerMyEnquiryView.as_view(), name="seller_my_enquiry"),
    path('seller/settings/',views.SellerSettingsView.as_view(), name="seller_settings"),

    path('seller/social-share/',views.SellerSocialShareView.as_view(), name="seller_social_share"),
    path('seller/paid-service/',views.SellerPaidServiceView.as_view(), name="seller_paid_service"),
    path('seller/management/',views.SellerManagementView.as_view(), name="seller_management"),
    path('seller/media-center/',views.SellerMediaCenterView.as_view(), name="seller_media_center"),

    path('seller/company/<str:user>/',views.SellerCompanyView.as_view(), name="seller_company"),
    path('seller/product-detail/<int:pk>/',views.SellerProductDetailView.as_view(), name="seller_product_detail"),

    path('seller/arrange-product/<int:pk>/',views.SellerArangeProductView.as_view(), name="seller_arrange_product"),
    path('seller/unarrange-product/<int:pk>/',views.SellerUnArangeProductView.as_view(), name="seller_unarrange_product"),

    path('seller/add-home-product/<int:pk>/',views.SellerAddHomeView.as_view(), name="seller_add_home_product"),
    path('seller/remove-home-product/<int:pk>/',views.SellerRemoveHomeView.as_view(), name="seller_remove_home_product"),

    path('seller/companey-add/',views.SellersCompanyView, name="seller_company_add"),


    ####################################### Buyer #####################################
    path('buyer-dashboard/',views.BuyerDashboardView.as_view(), name="buyer_dashboard"),
    path('buyer-profile/',views.BuyerProfileView.as_view(), name="buyer_profile"),
    path('buyer-order/',views.BuyerOrderView.as_view(), name="buyer_order"),
    path('buyer-message/',views.BuyerMessageView.as_view(), name="buyer_message"),
    path('buyer-offer-request-detail/',views.BuyerOfferRequestDetailsView.as_view(), name="buyer_offer_request_detail"),
    path('buyer-enquiry/',views.BuyerEnquiryView.as_view(), name="buyer_enquiry"),
    path('buyer-recent-activity/',views.BuyerRecentActivityView.as_view(), name="buyer_recent_activity"),
    path('buyer-favourite/',views.BuyerFavouriteView.as_view(), name="buyer_favourite"),
    path('buyer-downloads/',views.BuyerDownloadsView.as_view(), name="buyer_downloads"),
    path('buyer-share/',views.BuyerShareView.as_view(), name="buyer_share"),

    path('share-detail/<str:slug>/',views.ShareDetailView.as_view(), name="share_detail"),
    path('category/', views.category, name="category"),


    path('add-to-cart/<pk>/', views.add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<pk>/', views.remove_from_cart, name='remove-from-cart'),
    path('remove-product-from-cart/<pk>/', views.remove_single_product_from_cart, name='remove-single-product-from-cart'),
    path('cart/', views.CartView.as_view(), name='cart'),


    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('add-coupon/', views.AddCouponView.as_view(), name='add-coupon'),


]

product/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name="product"

urlpatterns = [
    path("",views.HomeView, name="home_list"),
    path("category/",views.category, name="category"),
    # path(r'^homescroll/$',views.homescroll, name="homescroll"),
    path("<str:slug>/",views.WebsiteHomeList.as_view(), name="website_home_list")
]

templates/template_blocks/footers.html
{% load static %}
 <div class="newstetter text-center pt-4 pb-4 mt-5">
      <h2 class="text-uppercase"><span>subscribe</span> to our newsletter</h2>
      <small>The best B2B news for manufactur and traders</small>
      <div class="input-group col-6 offset-3 mt-4">
        <input type="text" class="form-control" placeholder="Enter your email" aria-label="Enter your email" aria-describedby="subscribe">
        <div class="input-group-append">
          <span class="input-group-text" id="subscribe">Subscribe</span>
        </div>
      </div>
    </div>

    <footer class="pt-5 pb-5">
      <div class="container">
        <div class="row">
          <div class="col-12 col-sm-6 col-lg-2">
            <a href="{% url 'product:home_list' %}">
              <img src="{% static 'images/footerLogo.png' %}" alt="">
            </a>
          </div>
          <div class="col-12 col-sm-6 col-lg-2">
            <ul>
              <li class="head">About Us</li>
              <li><a href="{% url 'about_us' %}">XXX Mart</a></li>
              <li><a href="{% url 'about_management' %}">Management Team</a></li>
              <li><a href="{% url 'about_media_center' %}">Media Center</a></li>
              <li><a href="{% url 'about_work_with_us' %}">Work With Us</a></li>
              <li><a href="{% url 'about_contact_us' %}">Contact Us</a></li>
            </ul>
          </div>
          <div class="col-12 col-sm-6 col-lg-3">
            <ul>
              <li class="head">Customer Services</li>
              <li><a href="{% url 'help_center' %}">Help Center</a></li>
              <li><a href="{% url 'privacy_policy' %}">privacy policy</a></li>
              <li><a href="{% url 'trading_policy' %}">Trading policy</a></li>
              <li><a href="{% url 'term_condition' %}">terms & conditons</a></li>
              <!-- <li><a href="{% url 'edit_profile' %}">edit Profile</a></li> -->
            </ul>
          </div>
          <div class="col-12 col-sm-6 col-lg-3">
            <ul>
              <li class="head">E-Trade Service</li>
              <li><a href="{% url 'certificate' %}">XXXXXXXXX Certificate</a></li>
              {% comment %}<li><a href="{% url 'dashboard:seller_company' %}">E-Shoppe Development</a></li>{% endcomment %}
              <li><a href="{% url 'media_center' %}">Media Center</a></li>
              <li><a href="{% url 'advertise' %}">Adverties Your Brand</a></li>
              <!-- <li><a href="#">Transact To Trade</a></li> -->
            </ul>
          </div>
          <div class="col-12 col-sm-6 col-lg-2">
            <ul>
              <li class="head">Follow us</li>
              <li>
                <a href=""><img src="{% static 'images/fb.png' %}" alt=""></a>
                <a href=""><img src="{% static 'images/tw.png' %}" alt=""></a>
                <a href=""><img src="{% static 'images/lindin.png' %}" alt=""></a>
                <a href=""><img src="{% static 'images/youtube.png' %}" alt=""></a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
    <div class="copyright text-center pt-3 pb-3">
      <p class="mb-3">&#169; 2021 XXXXXXXXXXXX Mart</p>
      <img src="{% static 'images/footerSub.png' %}" alt="">
    </div>

templates/template_blocks/head_css.html
{% load static %}
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
<link rel="stylesheet" type="text/css" href="http://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/><!-- CSS -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<link rel="stylesheet" href="{% static 'css/app.css' %}">
<title>XXXX Mart</title>
{% block extra_css %}
{% endblock extra_css %}

templates/template_blocks/javascript.html
{% load static %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.3/dist/jquery.validate.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="{%static 'js/register.js' %}"></script>


    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script type="text/javascript" src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
    <script src="{% static 'js/app.js' %}"></script>

templates/template_blocks/navbar.html
{% load static %}
{% load cart_template_tags %}
{% include 'template_blocks/head_css.html' %}
<nav class="navbar navbar-expand-lg navbar-light bg-primary">
  <div class="container">
    <a class="navbar-brand" href="/">
      <img src="{% static 'images/logo.png' %}" alt="">
      <span class="ml-5">| <i>Desh Ka Vyapar</i></span>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav m-auto w-33">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'certificate' %}"><span class="critificate-bg">Apply For Unique xxxxxxxxx Certification</span></a>
        </li>
        {% if request.user.account.business_type == "Seller" %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'dashboard:seller_dashboard' %}">Seller</a>
        </li>
        {% elif request.user.account.business_type == "Buyer" %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'dashboard:buyer_dashboard' %}">Buyer</a>
        </li>
        {% endif %}

        {% if not request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'dashboard:seller_dashboard' %}">Seller</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'dashboard:buyer_dashboard' %}">Buyer</a>
        </li>
        {% endif %}

        <li class="nav-item">
          <a class="nav-link" href="{% url 'help' %}">Help</a>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto right">
        
        {% if request.user.is_authenticated %}  
       
        <li class="nav-item track-order">
          <a class="nav-link" href="{% url 'order_track' %}">
            <img src="{% static 'images/trackorder.png' %}" alt="">
            <span>Track Order</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link cart" href="{% url 'dashboard:cart' %}"> 
            <img src="{% static 'images/cart.png' %}" alt="">
            <span>My Cart</span>
            <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_product_count }} </span>
          </a>
        </li>
        <li class="nav-item login">
          <a class="nav-link" href="{% url 'account_logout' %}">
            <img src="{% static 'images/login.png' %}" alt="">
            <span>Log Out</span>
          </a>
        </li>
        {% else %}
        <li class="nav-item login">
          <a class="nav-link" href="{% url 'account_login' %}">
            <img src="{% static 'images/login.png' %}" alt="">
            <span>Log in New User</span>
          </a>
        </li>
        
        {% endif %}
        
        <li class="nav-item">
          <a class="nav-link pr-0" href="{% url 'advertise' %}">
            <img src="{% static 'images/advertizment.png' %}" alt="">
            <span>Advertizment with us</span>
          </a>
        </li>
      </ul>
    </div>
  </div>
</nav>