b2bmart/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('help/', TemplateView.as_view(template_name="help.html"), name="help"),

    path('about-us/', TemplateView.as_view(template_name="company/about-us.html"), name="about_us"),
    path('about-management/', TemplateView.as_view(template_name="company/management.html"), name="about_management"),
    path('about-media-center/', TemplateView.as_view(template_name="company/media-center.html"), name="about_media_center"),
    path('about-work-with-us/', TemplateView.as_view(template_name="company/workWithUs.html"), name="about_work_with_us"),
    path('about-contact-us/', TemplateView.as_view(template_name="company/contact-us.html"), name="about_contact_us"),
    path('help-center/', TemplateView.as_view(template_name="company/help.html"), name="help_center"),
    path('privacy-policy/', TemplateView.as_view(template_name="company/privacy-policy.html"), name="privacy_policy"),
    path('trading-policy/', TemplateView.as_view(template_name="company/trading-policy.html"), name="trading_policy"),
    path('term-condition/', TemplateView.as_view(template_name="company/term-condition.html"), name="term_condition"),
    path('edit-profile/', TemplateView.as_view(template_name="company/seller/user.html.html"), name="edit_profile"),
    path('certificate/', TemplateView.as_view(template_name="company/certificate.html"), name="certificate"),
    path('media-center/', TemplateView.as_view(template_name="company/media-center.html"), name="media_center"),
    path('advertise/', TemplateView.as_view(template_name="company/advertise.html"), name="advertise"),

    path('order-track/', TemplateView.as_view(template_name="company/ordertrack.html"), name="order_track"),
    #path('cart/', TemplateView.as_view(template_name="company/cart.html"), name="cart"),

    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('accounts/', include('allauth.urls')),
    path('', include("product.urls", namespace="product")),
    path('dashboard/', include('dashboard.urls', namespace="dashboard")),

    

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dashboard/urls.py
from django.urls import path
from . import views
app_name = "dashboard"

urlpatterns = [
    path('seller-dashboard/',views.SellerDashboardView.as_view(), name="seller_dashboard"),
    path('seller/contact-profile/',views.SellerContactProfileView.as_view(), name="seller_contact_profile"),
    path('seller/business-profile/',views.SellerBusinessProfileView, name="seller_business_profile"),
    path('seller/statutory/',views.SellerStatutoryView.as_view(), name="seller_statutory"),
    path('seller/bank/',views.SellerBankView.as_view(), name="seller_bank"),
    
    
    
    path('seller/add-product/',views.SellerAddProductView.as_view(), name="seller_add_product"),
    path('seller/manage-product/',views.SellerManageProductView, name="seller_manage_product"),
    path('seller/rearrange-product/',views.SellerReArrangeProductView.as_view(), name="seller_rearrange_product"),
    path('seller/bulk-price-update/<str:pk>',views.SellerBulkPriceUpdateView, name="seller_bulk_price_update"),
    path('seller/single-product-update/<str:pk>', views.SellerSingleProductUpdateView, name="seller_single_product_update"),
    path('<int:pk>/delete_product/', views.sellerDeleteProduct, name="seller_delete_product"),
    path('seller/category-report/',views.SellerCategoryReportView.as_view(), name="seller_category_report"),
    path('seller/analytics/',views.SellerAnalyticView.as_view(), name="seller_analytics"),
    

    path('seller/business-outlook/',views.SellerBusinessOutlookView.as_view(), name="seller_business_outlook"),
    path('seller/finance/',views.SellerFinancecView.as_view(), name="seller_finance"),
    path('seller/history/',views.SellerHistoryView.as_view(), name="seller_history"),
    path('seller/document/',views.SellerPhotoDocumentView.as_view(), name="seller_document"),
    path('seller/membership/',views.SellerMembershipView.as_view(), name="seller_membership"),
    path('seller/my-enquiry/',views.SellerMyEnquiryView.as_view(), name="seller_my_enquiry"),
    path('seller/settings/',views.SellerSettingsView.as_view(), name="seller_settings"),

    path('seller/social-share/',views.SellerSocialShareView.as_view(), name="seller_social_share"),
    path('seller/paid-service/',views.SellerPaidServiceView.as_view(), name="seller_paid_service"),
    path('seller/management/',views.SellerManagementView.as_view(), name="seller_management"),
    path('seller/media-center/',views.SellerMediaCenterView.as_view(), name="seller_media_center"),

    path('seller/company/<str:user>/',views.SellerCompanyView.as_view(), name="seller_company"),
    path('seller/product-detail/<int:pk>/',views.SellerProductDetailView.as_view(), name="seller_product_detail"),

    path('seller/arrange-product/<int:pk>/',views.SellerArangeProductView.as_view(), name="seller_arrange_product"),
    path('seller/unarrange-product/<int:pk>/',views.SellerUnArangeProductView.as_view(), name="seller_unarrange_product"),

    path('seller/add-home-product/<int:pk>/',views.SellerAddHomeView.as_view(), name="seller_add_home_product"),
    path('seller/remove-home-product/<int:pk>/',views.SellerRemoveHomeView.as_view(), name="seller_remove_home_product"),

    path('seller/companey-add/',views.SellersCompanyView, name="seller_company_add"),


    ####################################### Buyer #####################################
    path('buyer-dashboard/',views.BuyerDashboardView.as_view(), name="buyer_dashboard"),
    path('buyer-profile/',views.BuyerProfileView.as_view(), name="buyer_profile"),
    path('buyer-order/',views.BuyerOrderView.as_view(), name="buyer_order"),
    path('buyer-message/',views.BuyerMessageView.as_view(), name="buyer_message"),
    path('buyer-offer-request-detail/',views.BuyerOfferRequestDetailsView.as_view(), name="buyer_offer_request_detail"),
    path('buyer-enquiry/',views.BuyerEnquiryView.as_view(), name="buyer_enquiry"),
    path('buyer-recent-activity/',views.BuyerRecentActivityView.as_view(), name="buyer_recent_activity"),
    path('buyer-favourite/',views.BuyerFavouriteView.as_view(), name="buyer_favourite"),
    path('buyer-downloads/',views.BuyerDownloadsView.as_view(), name="buyer_downloads"),
    path('buyer-share/',views.BuyerShareView.as_view(), name="buyer_share"),

    path('share-detail/<str:slug>/',views.ShareDetailView.as_view(), name="share_detail"),
    path('category/', views.category, name="category"),


    path('add-to-cart/<pk>/', views.add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<pk>/', views.remove_from_cart, name='remove-from-cart'),
    path('remove-product-from-cart/<pk>/', views.remove_single_product_from_cart, name='remove-single-product-from-cart'),
    path('cart/', views.CartView.as_view(), name='cart'),


    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('add-coupon/', views.AddCouponView.as_view(), name='add-coupon'),


]

dashboard/models.py
from django.db import models
from accounts.models import Account
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from embed_video.fields import EmbedVideoField
from product.models import Product



class SellerProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    promoter_first_name = models.CharField(max_length=50)
    promoter_last_name = models.CharField(max_length=50)
    designation = models.CharField(max_length=50)
    address_building = models.CharField(max_length=100)
    address_area = models.CharField(max_length=100)
    landmark = models.CharField(max_length=50)
    locality = models.CharField(max_length=50)
    country = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    gstin = models.CharField(max_length=50)
    company_website = models.CharField(max_length=50)
    alternative_mobile = models.CharField(max_length=50)
    alternative_email = models.EmailField(max_length=50)
    landline_no = models.CharField(max_length=50)
    alternative_landline_no = models.CharField(max_length=50)
    about_me = models.TextField()

    def __str__(self):
        return self.user.username



def validate_image(fieldfile_obj):
    filesize = fieldfile_obj.file.size
    megabyte_limit = 2.0
    if filesize > megabyte_limit*1024*1024:
        raise ValidationError("Max file size is %sMB" % str(megabyte_limit))


class BusinessProfile(models.Model):
    CATEGORY = (
			('Seller', 'Seller'),
			('Manufacturer', 'Manufacturer'),
			) 
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='businessprofile')
    company_name = models.CharField(max_length=200, blank=True, null=True)
    year_of_establishment = models.DateField(blank=True, null=True)
    phone = models.CharField(max_length=200, blank=True, null=True)
    category = models.CharField(max_length=200, blank=True, null=True, choices=CATEGORY)
    annual_turnover = models.CharField(max_length=200, blank=True, null=True)
    company_card_front_view = models.ImageField(default="company_card.png", upload_to='images/', validators=[validate_image], null=True, blank=True, help_text='Maximum file size allowed is 2Mb')
    company_card_back_view = models.ImageField(default="company_card.png", upload_to='images/', validators=[validate_image], null=True, blank=True, help_text='Maximum file size allowed is 2Mb')
    
    def __str__(self):
        return self.user.username

      
class SellerStatutory(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    gst_no = models.CharField(max_length=50, null=True)
    pan_no = models.CharField(max_length=50, null=True)
    tan_no = models.CharField(max_length=50, null=True)
    cin_no = models.CharField(max_length=100, null=True)
    dgft_ie_code = models.CharField(max_length=100, null=True)
    company_registration_no = models.URLField(max_length=50, null=True)

    def __str__(self):
        return self.user.username
    

class SellerBank(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bank_name = models.CharField(max_length=50)
    account_no = models.CharField(max_length=50)
    bank_account_name = models.CharField(max_length=50)
    ifsc_code = models.CharField(max_length=50)
    account_type = models.CharField(max_length=50)
    alternative_bank_name = models.CharField(max_length=50)
    alternative_account_no = models.CharField(max_length=50)
    alternative_bank_account_name = models.CharField(max_length=50)
    alternative_bank_ifsc_code = models.CharField(max_length=50)
    alternative_bank_account_type = models.CharField(max_length=50)

    def __str__(self):
        return self.user.username



from django.db.models.signals import post_save
def businessprofile_receiver(sender, instance, created, *args, **kwargs):
    if created:
        userprofile = BusinessProfile.objects.create(user=instance)


post_save.connect(businessprofile_receiver, sender=User)

class SellerCompany(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='sellercompany')
    about_seller = models.TextField(blank=True, null=True)
    no_of_employees = models.PositiveIntegerField(blank=True, null=True)
    legal_status_of_firm = models.CharField(max_length=50)
    catalogue = models.FileField(upload_to="files/seller_catalogues", blank=True, null=True)
    branded_video = EmbedVideoField()
    caption = models.CharField(max_length=200, blank=True, null=True)
    logo = models.ImageField(default="company_card.png", upload_to="images/seller_logos")
    banner_image =models.ImageField(default="company_card.png", upload_to="images/seller_banner_images")
     
    def __str__(self):
        return self.user.username


def sellercompany_receiver(sender, instance, created, *args, **kwargs):
    if created:
        userprofile = SellerCompany.objects.create(user=instance)

post_save.connect(sellercompany_receiver, sender=User)

BUSINESS_TYPE_CHOICES = (
        ('Manufacturer', 'Manufacturer'),
        ('Retailer', 'Retailer'),
        ('Distributer', 'Distributer'),
        ('Wholeseller', 'Wholeseller'),
        ('Exporter', 'Exporter'),
)
class ShareDetail(models.Model):
    seller = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=100)
    mobile = models.IntegerField()
    business_type = models.CharField(max_length=20, choices=BUSINESS_TYPE_CHOICES)
    message = models.TextField()
    send_copy = models.BooleanField(default=False)
    
    def __str__(self):
        return str(self.name) 

templates/dashboard/seller/analytics.html
    {% extends 'dashboard/seller/seller_base.html' %}
    {% load static %}
       {% block content %}
    <div class="main-panel">
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            <a class="navbar-brand" href="javascript:;">Analytics</a>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="sr-only">Toggle navigation</span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-end">
            <form class="navbar-form">
              <div class="input-group no-border">
                <input type="text" value="" class="form-control" placeholder="Search...">
                <button type="submit" class="btn btn-white btn-round btn-just-icon">
                  <i class="material-icons">search</i>
                  <div class="ripple-container"></div>
                </button>
              </div>
            </form>
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="javascript:;">
                  <i class="material-icons">dashboard</i>
                  <p class="d-lg-none d-md-block">
                    Stats
                  </p>
                </a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="material-icons">notifications</i>
                  <span class="notification">5</span>
                  <p class="d-lg-none d-md-block">
                    Some Actions
                  </p>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="#">Mike John responded to your email</a>
                  <a class="dropdown-item" href="#">You have 5 new tasks</a>
                  <a class="dropdown-item" href="#">You're now friend with Andrew</a>
                  <a class="dropdown-item" href="#">Another Notification</a>
                  <a class="dropdown-item" href="#">Another One</a>
                </div>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link" href="javascript:;" id="navbarDropdownProfile" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="material-icons">person</i>
                  <p class="d-lg-none d-md-block">
                    Account
                  </p>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownProfile">
                  <a class="dropdown-item" href="#">Profile</a>
                  <a class="dropdown-item" href="#">Settings</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="#">Log out</a>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      <!-- End Navbar -->
      <div class="content">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-12">
              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title">Edit Profile</h4>
                  <p class="card-category">Complete your profile</p>
                </div>
                <div class="card-body">
                  <div class="row">
                    <div class="col-md-9">
                      <img class="img-fluid" src="{% static 'seller/assets/img/calender.jpg' %}" alt="">
                    </div>
                    <div class="col-md-3">
                      <img class="img-fluid" src="{% static 'seller/assets/img/manufacture-dashbord-edited-copy.jpg' %}" alt="">
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-md-7 mt-3">
                      <img class="img-fluid" src="{% static 'seller/assets/img/sales-to-date.png" alt="">
                      <img class="img-fluid" src="{% static 'seller/assets/img/product-performance.png" alt="">
                    </div>
                    <div class="col-md-5 mt-3">
                      <img class="img-fluid" src="{% static 'seller/assets/img/sales-by-region.png" alt="">
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-md-12 mt-3">
                      <img class="img-fluid w-100" src="{% static 'seller/assets/img/Recent-Tickets.jpg' %}" alt="">
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% endblock content %}

templates/dashboard/seller/bank_details.html
{% extends 'dashboard/seller/seller_base.html' %}
{% load static %}
   {% block content %}
   <!-- Showing the Error message in red while validating form -->
        <style>
            .error{
            color:red;
            font-style:italic;
                    }
                    .bmd-form-group label {
                        color: red;
                        }
        </style>
        <!---->
   <!-- <h4 class="text-center">{{form.as_p}}</h4> -->
        <div class="main-panel">
            <!-- Navbar -->
            <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
                <div class="container-fluid">
                    <div class="navbar-wrapper">
                        <a class="navbar-brand" href="javascript:;">User Profile</a>
                    </div>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="sr-only">Toggle navigation</span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
          </button>
                    <div class="collapse navbar-collapse justify-content-end">
                        <form class="navbar-form">
                            <div class="input-group no-border">
                                <input type="text" value="" class="form-control" placeholder="Search...">
                                <button type="submit" class="btn btn-white btn-round btn-just-icon">
                  <i class="material-icons">search</i>
                  <div class="ripple-container"></div>
                </button>
                            </div>
                        </form>
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link" href="javascript:;">
                                    <i class="material-icons">dashboard</i>
                                    <p class="d-lg-none d-md-block">
                                        Stats
                                    </p>
                                </a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="material-icons">notifications</i>
                                    <span class="notification">5</span>
                                    <p class="d-lg-none d-md-block">
                                        Some Actions
                                    </p>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                                    <a class="dropdown-item" href="#">Mike John responded to your email</a>
                                    <a class="dropdown-item" href="#">You have 5 new tasks</a>
                                    <a class="dropdown-item" href="#">You're now friend with Andrew</a>
                                    <a class="dropdown-item" href="#">Another Notification</a>
                                    <a class="dropdown-item" href="#">Another One</a>
                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link" href="javascript:;" id="navbarDropdownProfile" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="material-icons">person</i>
                                    <p class="d-lg-none d-md-block">
                                        Account
                                    </p>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownProfile">
                                    <a class="dropdown-item" href="#">Profile</a>
                                    <a class="dropdown-item" href="#">Settings</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="{% url 'account_logout' %}">Log out</a>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
            <!-- End Navbar -->
            <div class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="card">
                                <div class="card-header card-header-primary">
                                    <h4 class="card-title">Bank Details</h4>
                                    <p class="card-category">Complete your bank details</p>
                                </div>
                                <div class="card-body">
                                    <form action="." method="post" id="Bank_detail">
                                        {% csrf_token %}
                                        <div class="row">
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label class="bmd-label-floating" for id="id_bank_name">Bank Name</label>
                                                    <input type="text" class="form-control" name="bank_name"id="id_bank_name" value="{{ seller_bank.bank_name }}">
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label class="bmd-label-floating" for id="id_account_no">Bank Account No.</label>
                                                    <input type="text" class="form-control" name="account_no"id="id_account_no" value="{{ seller_bank.account_no }}">
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label class="bmd-label-floating"for id="id_bank_account_name">Bank According Your Name</label>
                                                    <input type="text" class="form-control" name="bank_account_name"id="id_bank_account_name" value="{{ seller_bank.bank_account_name}}">
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label class="bmd-label-floating"for id="id_ifsc_code">Bank IFSC Code</label>
                                                    <input type="text" class="form-control" name="ifsc_code"id="id_ifsc_code" value="{{ seller_bank.ifsc_code }}">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label class="bmd-label-floating"for id="id_account_type">Account Type</label>
                                                    <input type="text" class="form-control" name="account_type"id="id_account_type" value="{{ seller_bank.account_type }}">
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label class="bmd-label-floating"for id="id_alternative_bank_name">Alernative Bank Name</label>
                                                    <input type="text" class="form-control" name="alternative_bank_name"id="id_alternative_bank_name" value="{{ seller_bank.alternative_bank_name }}">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label class="bmd-label-floating"for id="id_alternative_account_no">Alernative Bank Account No.</label>
                                                    <input type="text" class="form-control" name="alternative_account_no"id="id_alternative_account_no" value="{{ seller_bank.alternative_account_no }}">
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label class="bmd-label-floating"for id="id_alternative_bank_account_name">Alernative Bank According Your Name</label>
                                                    <input type="text" class="form-control" name="alternative_bank_account_name"id="id_alternative_bank_account_name" value="{{ seller_bank.alternative_bank_account_name }}">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label class="bmd-label-floating"for id="id_alternative_bank_ifsc_code">Alernative Bank IFSC Code</label>
                                                    <input type="text" class="form-control" name="alternative_bank_ifsc_code"id="id_alternative_bank_ifsc_code" value="{{ seller_bank.alternative_bank_ifsc_code }}">
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label class="bmd-label-floating"for id="id_alternative_bank_account_type">Alernative Account Type</label>
                                                    <input type="text" class="form-control" name="alternative_bank_account_type"id="id_alternative_bank_account_type" value="{{ seller_bank.alternative_bank_account_type }}">
                                                </div>
                                            </div>
                                        </div>
                                        <input type="submit" class="btn btn-primary pull-right" value="save">
                                        <div class="clearfix"></div>
                                    </form>
                                </div>
                            </div>
                            <!-- <div class="col-md-4">
                            <div class="card card-profile">
                                <div class="card-avatar">
                                    <a href="javascript:;">
                                        <img class="img" src="../images/cooker.jpg" />
                                    </a>
                                </div>
                                <div class="card-body">
                                    <h6 class="card-category text-gray">Company Name</h6>
                                    <h4 class="card-title">XXXX Mart</h4>
                                    <p class="card-description">
                                        Don't be scared of the truth because we need to restart the human foundation in truth And I love you like Kanye loves Kanye I love Rick Owens’ bed design but the back is...
                                    </p> -->
                            <!-- <a href="javascript:;" class="btn btn-primary btn-round">Follow</a> -->
                            <!-- </div>
                            </div>-->
                            <!-- </div> -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endblock content %}
          