b2bmart/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('help/', TemplateView.as_view(template_name="help.html"), name="help"),

    path('about-us/', TemplateView.as_view(template_name="company/about-us.html"), name="about_us"),
    path('about-management/', TemplateView.as_view(template_name="company/management.html"), name="about_management"),
    path('about-media-center/', TemplateView.as_view(template_name="company/media-center.html"), name="about_media_center"),
    path('about-work-with-us/', TemplateView.as_view(template_name="company/workWithUs.html"), name="about_work_with_us"),
    path('about-contact-us/', TemplateView.as_view(template_name="company/contact-us.html"), name="about_contact_us"),
    path('help-center/', TemplateView.as_view(template_name="company/help.html"), name="help_center"),
    path('privacy-policy/', TemplateView.as_view(template_name="company/privacy-policy.html"), name="privacy_policy"),
    path('trading-policy/', TemplateView.as_view(template_name="company/trading-policy.html"), name="trading_policy"),
    path('term-condition/', TemplateView.as_view(template_name="company/term-condition.html"), name="term_condition"),
    path('edit-profile/', TemplateView.as_view(template_name="company/seller/user.html.html"), name="edit_profile"),
    path('certificate/', TemplateView.as_view(template_name="company/certificate.html"), name="certificate"),
    path('media-center/', TemplateView.as_view(template_name="company/media-center.html"), name="media_center"),
    path('advertise/', TemplateView.as_view(template_name="company/advertise.html"), name="advertise"),

    path('order-track/', TemplateView.as_view(template_name="company/ordertrack.html"), name="order_track"),
    #path('cart/', TemplateView.as_view(template_name="company/cart.html"), name="cart"),

    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('accounts/', include('allauth.urls')),
    path('', include("product.urls", namespace="product")),
    path('dashboard/', include('dashboard.urls', namespace="dashboard")),

    

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dashboard/urls.py
from django.urls import path
from . import views
app_name = "dashboard"

urlpatterns = [
    path('seller-dashboard/',views.SellerDashboardView.as_view(), name="seller_dashboard"),
    path('seller/contact-profile/',views.SellerContactProfileView.as_view(), name="seller_contact_profile"),
    path('seller/business-profile/',views.SellerBusinessProfileView, name="seller_business_profile"),
    path('seller/statutory/',views.SellerStatutoryView.as_view(), name="seller_statutory"),
    path('seller/bank/',views.SellerBankView.as_view(), name="seller_bank"),
    
    
    
    path('seller/add-product/',views.SellerAddProductView.as_view(), name="seller_add_product"),
    path('seller/manage-product/',views.SellerManageProductView, name="seller_manage_product"),
    path('seller/rearrange-product/',views.SellerReArrangeProductView.as_view(), name="seller_rearrange_product"),
    path('seller/bulk-price-update/<str:pk>',views.SellerBulkPriceUpdateView, name="seller_bulk_price_update"),
    path('seller/single-product-update/<str:pk>', views.SellerSingleProductUpdateView, name="seller_single_product_update"),
    path('<int:pk>/delete_product/', views.sellerDeleteProduct, name="seller_delete_product"),
    path('seller/category-report/',views.SellerCategoryReportView.as_view(), name="seller_category_report"),
    path('seller/analytics/',views.SellerAnalyticView.as_view(), name="seller_analytics"),
    

    path('seller/business-outlook/',views.SellerBusinessOutlookView.as_view(), name="seller_business_outlook"),
    path('seller/finance/',views.SellerFinancecView.as_view(), name="seller_finance"),
    path('seller/history/',views.SellerHistoryView.as_view(), name="seller_history"),
    path('seller/document/',views.SellerPhotoDocumentView.as_view(), name="seller_document"),
    path('seller/membership/',views.SellerMembershipView.as_view(), name="seller_membership"),
    path('seller/my-enquiry/',views.SellerMyEnquiryView.as_view(), name="seller_my_enquiry"),
    path('seller/settings/',views.SellerSettingsView.as_view(), name="seller_settings"),

    path('seller/social-share/',views.SellerSocialShareView.as_view(), name="seller_social_share"),
    path('seller/paid-service/',views.SellerPaidServiceView.as_view(), name="seller_paid_service"),
    path('seller/management/',views.SellerManagementView.as_view(), name="seller_management"),
    path('seller/media-center/',views.SellerMediaCenterView.as_view(), name="seller_media_center"),

    path('seller/company/<str:user>/',views.SellerCompanyView.as_view(), name="seller_company"),
    path('seller/product-detail/<int:pk>/',views.SellerProductDetailView.as_view(), name="seller_product_detail"),

    path('seller/arrange-product/<int:pk>/',views.SellerArangeProductView.as_view(), name="seller_arrange_product"),
    path('seller/unarrange-product/<int:pk>/',views.SellerUnArangeProductView.as_view(), name="seller_unarrange_product"),

    path('seller/add-home-product/<int:pk>/',views.SellerAddHomeView.as_view(), name="seller_add_home_product"),
    path('seller/remove-home-product/<int:pk>/',views.SellerRemoveHomeView.as_view(), name="seller_remove_home_product"),

    path('seller/companey-add/',views.SellersCompanyView, name="seller_company_add"),


    ####################################### Buyer #####################################
    path('buyer-dashboard/',views.BuyerDashboardView.as_view(), name="buyer_dashboard"),
    path('buyer-profile/',views.BuyerProfileView.as_view(), name="buyer_profile"),
    path('buyer-order/',views.BuyerOrderView.as_view(), name="buyer_order"),
    path('buyer-message/',views.BuyerMessageView.as_view(), name="buyer_message"),
    path('buyer-offer-request-detail/',views.BuyerOfferRequestDetailsView.as_view(), name="buyer_offer_request_detail"),
    path('buyer-enquiry/',views.BuyerEnquiryView.as_view(), name="buyer_enquiry"),
    path('buyer-recent-activity/',views.BuyerRecentActivityView.as_view(), name="buyer_recent_activity"),
    path('buyer-favourite/',views.BuyerFavouriteView.as_view(), name="buyer_favourite"),
    path('buyer-downloads/',views.BuyerDownloadsView.as_view(), name="buyer_downloads"),
    path('buyer-share/',views.BuyerShareView.as_view(), name="buyer_share"),

    path('share-detail/<str:slug>/',views.ShareDetailView.as_view(), name="share_detail"),
    path('category/', views.category, name="category"),


    path('add-to-cart/<pk>/', views.add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<pk>/', views.remove_from_cart, name='remove-from-cart'),
    path('remove-product-from-cart/<pk>/', views.remove_single_product_from_cart, name='remove-single-product-from-cart'),
    path('cart/', views.CartView.as_view(), name='cart'),


    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('add-coupon/', views.AddCouponView.as_view(), name='add-coupon'),


]

templates/company/advertise.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
      <div class="row">
        <div class="col-12 col-sm-3 bg-primary pl-0 pr-0 mt-4">
          <ul class="nav flex-column pt-3">
            <li class="nav-item"><a class="nav-link" href="{% url 'about_us' %}">XXX Mart</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'about_management' %}">Management Team</a></li>
            <li class="nav-item"><a class="nav-link active" href="{% url 'about_media_center' %}">Media Center</a></li>
            <!-- <li class="nav-item"><a class="nav-link" href="contact-us.html">Contact Us</a></li> -->
            <li class="nav-item"><a class="nav-link" href="{% url 'certificate' %}">XXXXXXXXX Certificate</a></li>
            <!-- <li class="nav-item"><a class="nav-link" href="company.html">E-Shoppe Development</a></li> -->
            <li class="nav-item"><a class="nav-link" href="{% url 'advertise' %}">Adverties Your Brand</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'privacy_policy' %}">privacy policy</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'term_condition' %}">terms & conditons</a></li>
            <!-- <li class="nav-item"><a class="nav-link" href="seller/user.html">edit Profile</a></li> -->
            </li>
          </ul>
        </div>
        <div class="col-12 col-sm-9">
          <div class="card mt-4">
            <div class="card-header card-header-primary">
              <h4>Get the <b>TOP POSITION,</b> place your AD with XXXX</h4>
            </div>
            <div class="card-body">
              <form>
                <div class="row">
                  <div class="col-md-6">
                    <div class="form-group">
                      <label class="h6">Company</label>
                      <input type="text" class="form-control">
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label class="h6">Email address</label>
                      <input type="email" class="form-control">
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-6">
                    <div class="form-group">
                      <label class="h6">Fist Name</label>
                      <input type="text" class="form-control">
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label class="h6">Last Name</label>
                      <input type="text" class="form-control">
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-6">
                    <div class="form-group">
                      <label class="h6">Mobile No</label>
                      <input type="text" class="form-control">
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label class="h6">Landline Number</label>
                      <input type="text" class="form-control">
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="category" class="h6">category</label>
                      <select class="form-control" id="category">
                        <option>Kitchen stoves</option>
                        <option>Mixer Grinder</option>
                        <option>Rice cookers</option>
                        <option>Food processors</option>
                        <option>Electric mixers</option>
                      </select>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="category" class="h6">Add Impressions</label>
                      <select class="form-control" id="category">
                        <option>1000-5000</option>
                        <option>5000-10000</option>
                        <option>10000-15000</option>
                        <option>Other Option</option>
                      </select>
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-12">
                    <div class="form-group">
                      <label>Share with us</label>
                      <div class="form-group">
                        <!-- <label class="h6"> Lamborghini Mercy, Your chick she so thirsty, I'm in that two seat Lambo.</label> -->
                        <textarea class="form-control" rows="3"></textarea>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="text-right">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
            </div>
          </div> 
        </div>
      </div>
    </div>
{% endblock content %}

templates/company/advertisementWithUs.html
    {% extends 'base.html' %}
    {% block content %}

    <div class="page-banner">
        <h1 class="display-5">Advertise Your Brand</h1>
    </div>
    <div class="container">
        <h3>Advertise with XxxxxxMart</h3>
        <p class="lead">Whether you are a large organisation, small business or a marketing agency, XxxxxxMart offers you a host of services for boosting your reach and connecting you with millions of buyers. We offer effective lead generation model and ROI driven marketing
            strategy.
        </p>
        <div class="page-cta">
            Trial For Free | Monthly Paid | Yearly Services
        </div>

        <img src="https://image.shutterstock.com/image-vector/setting-icon-vector-gear-cog-260nw-1211635549.jpg" alt="knowlege">
        <h3>If you&#8217;re a Big Business</h3>

        <p>1000+ large corporates have started their digital transformation journey and are promoting themselves online to grow their business through XxxxxxMart.</p>

        <img src="https://www.searchpng.com/wp-content/uploads/2019/02/Message-PNG-Icon.png" alt="knowlege">
        <h3>If you&#8217;re a Small, Medium Business</h3>
        <p>We’ve been the pioneers of taking small businesses online and helping them create their digital presence and making it easier for them to do business. </p>

        <img src="https://i.pinimg.com/originals/d3/fb/e4/d3fbe447d1e9745c6034c77de7fe4817.png" alt="strategy">
        <h3>If you&#8217;re a marketing agency</h3>
        <p>Make the most ROI driven lead generation platform, XxxxxxMart, an integral part of your client pitch.</p>
    </div>
{% endblock content %}

templates/company/cart.html
    {% extends 'base.html' %}
    {% block content %}
    <div class="px-4 px-lg-0 mt-4">
        <div class="pb-5">
          <div class="container">
            <div class="row">
              <div class="col-lg-12 p-5 bg-white rounded shadow-sm mb-5">
      
                <!-- Shopping cart table -->
                <div class="table-responsive">
                  <table class="table">
                    <thead>
                      <tr>
                        <th scope="col" class="border-0 bg-light">
                          <div class="p-2 px-3 text-uppercase">Product</div>
                        </th>
                        <th scope="col" class="border-0 bg-light">
                          <div class="py-2 text-uppercase">Price</div>
                        </th>
                        <th scope="col" class="border-0 bg-light">
                          <div class="py-2 text-uppercase">Quantity</div>
                        </th>
                        <th scope="col" class="border-0 bg-light">
                          <div class="py-2 text-uppercase">Total Product Price</div>
                        </th>
                        <th scope="col" class="border-0 bg-light">
                          <div class="py-2 text-uppercase">Remove</div>
                        </th>
                      </tr>
                    </thead>
                    <tbody>
                      {% for order_product in object.products.all %}
                      <tr>
                        <th scope="row" class="border-0">
                          <div class="p-2">
                            <img src="{{ order_product.product.image1.url }}" alt="" width="70" class="img-fluid rounded shadow-sm">
                            <div class="ml-3 d-inline-block align-middle">
                              <h5 class="mb-0"> <a href="#" class="text-dark d-inline-block align-middle">{{ order_product.product.name }}</a></h5><span class="text-muted font-weight-normal font-italic d-block">Category: {{ order_product.product.product_group }}</span>
                            </div>
                          </div>
                        </th>
                        <td class="border-0 align-middle"><strong>&#8377;{{ order_product.product.price }}</strong></td>
                        <td class="border-0 align-middle"><strong>
                          <a href="{% url 'dashboard:remove-single-product-from-cart' order_product.product.pk %}"><i class="fas fa-minus mr-2"></i></a>
                          {{ order_product.quantity }}
                          <a href="{% url 'dashboard:add-to-cart' order_product.product.pk %}"><i class="fas fa-plus ml-2"></i></a>
                        </strong></td>
                       
                        <td class="border-0 align-middle"><strong>
                          {% if order_product.product.discount_price %}
                          &#8377;{{order_product.get_total_discount_product_price}}
                          {% else %}
                          &#8377;{{order_product.get_total_product_price}}
                          {% endif %}
              
                        </strong></td>
                        <td class="border-0 align-middle"><a href="{% url 'dashboard:remove-from-cart' order_product.product.pk %}" class="text-danger"><i class="fa fa-trash"></i></a></td>
                      </tr>
                      {% empty %}
                      <tr>
                          <td colspan='5'>Your cart is empty</td>
                      </tr>
                      <tr>
                          <td colspan="5">
                          <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
                          </td>
                      </tr>
                     {% endfor %}
                     {% if object.get_total %}
                     <tr>
                         <td colspan="3"><b>Order Total</b></td>
                         <td><b>&#8377;{{ object.get_total }}</b></td>
                     </tr>
                     <tr>
                         <td colspan="5">
                         <a class='btn btn-warning float-right ml-2' href='{% url "dashboard:checkout" %}'>Proceed to checkout</a>
                         <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
                         </td>
                     </tr>
                     {% endif %}
                    </tbody>
                  </table>
                </div>
                <!-- End -->
              </div>
            </div>
      
            <div class="row py-5 p-4 bg-white rounded shadow-sm">
              <div class="col-lg-6">
                <div class="bg-light rounded-pill px-4 py-3 text-uppercase font-weight-bold">Coupon code</div>
                <div class="p-4">
                  <p class="font-italic mb-4">If you have a coupon code, please enter it in the box below</p>
                  <div class="input-group mb-4 border rounded-pill p-2">
                    <input type="text" placeholder="Apply coupon" aria-describedby="button-addon3" class="form-control border-0">
                    <div class="input-group-append border-0">
                      <button id="button-addon3" type="button" class="btn btn-primary px-4 rounded-pill"><i class="fa fa-gift mr-2"></i>Apply coupon</button>
                    </div>
                  </div>
                </div>
                <div class="bg-light rounded-pill px-4 py-3 text-uppercase font-weight-bold">Instructions for seller</div>
                <div class="p-4">
                  <p class="font-italic mb-4">If you have some information for the seller you can leave them in the box below</p>
                  <textarea name="" cols="30" rows="2" class="form-control"></textarea>
                </div>
              </div>
              <div class="col-lg-6">
                <div class="bg-light rounded-pill px-4 py-3 text-uppercase font-weight-bold">Order summary </div>
                <div class="p-4">
                  <p class="font-italic mb-4">Shipping and additional costs are calculated based on values you have entered.</p>
                  <ul class="list-unstyled mb-4">
                    <li class="d-flex justify-content-between py-3 border-bottom"><strong class="text-muted">Order Subtotal </strong><strong>$390.00</strong></li>
                    <li class="d-flex justify-content-between py-3 border-bottom"><strong class="text-muted">Shipping and handling</strong><strong>$10.00</strong></li>
                    <li class="d-flex justify-content-between py-3 border-bottom"><strong class="text-muted">Tax</strong><strong>$0.00</strong></li>
                    <li class="d-flex justify-content-between py-3 border-bottom"><strong class="text-muted">Total</strong>
                      <h5 class="font-weight-bold">$400.00</h5>
                    </li>
                  </ul><a href="#" class="btn btn-primary rounded-pill py-2 btn-block">Procceed to checkout</a>
                </div>
              </div>
            </div>
      
          </div>
        </div>
      </div>
{% endblock content %}
    

templates/company/checkout.html
{% extends "base.html" %}


{% block content %}

  <main >
    <div class="container wow fadeIn">
      <h2 class="my-5 h2 text-center">Checkout form</h2>
      <div class="row">
        <div class="col-md-8 mb-4">
          <div class="card">
            <form method="POST" class="card-body">
              {% csrf_token %}

              <h3>Shipping address</h3>

              <div class='hideable_shipping_form'>

                <div class="md-form mb-5">
                  <label for="shipping_address" class="">Address</label>
                  <input type='text' placeholder='1234 Main St' id='shipping_address' name='shipping_address' class='form-control' />
                  
                </div>

                <div class="md-form mb-5">
                  <label for="shipping_address2" class="">Address 2 (optional)</label>
                  <input type='text' placeholder='Apartment or suite' id='shipping_address2' name='shipping_address2' class='form-control' />
                  
                </div>

                <div class="row">
                  <div class="col-lg-4 col-md-12 mb-4">
                    <label for="country">Country</label>
                    {{ form.shipping_country }}
                    <div class="invalid-feedback">
                      Please select a valid country.
                    </div>
                  </div>
                  <div class="col-lg-4 col-md-6 mb-4">
                    <label for="shipping_zip">Zip</label>
                    <input type='text' placeholder='Zip code' id='shipping_zip' name='shipping_zip' class='form-control' />
                    <div class="invalid-feedback">
                      Zip code required.
                    </div>
                  </div>
                </div>

                <div class="custom-control custom-checkbox">
                  <input type="checkbox" class="custom-control-input" name="same_billing_address" id="same_billing_address">
                  <label class="custom-control-label" for="same_billing_address">Billing address is the same as my shipping address</label>
                </div>
                <div class="custom-control custom-checkbox">
                  <input type="checkbox" class="custom-control-input" name="set_default_shipping" id="set_default_shipping">
                  <label class="custom-control-label" for="set_default_shipping">Save as default shipping address</label>
                </div>

              </div>

              {% if default_shipping_address %}
              <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" name="use_default_shipping" id="use_default_shipping">
                <label class="custom-control-label" for="use_default_shipping">Use default shipping address: {{ default_shipping_address.street_address|truncatechars:10 }}</label>
              </div>
              {% endif %}

              <hr>

              <h3>Billing address</h3>

              <div class='hideable_billing_form'>
                <div class="md-form mb-5">
                  <label for="billing_address" class="">Address</label>
                  <input type='text' placeholder='1234 Main St' id='billing_address' name='billing_address' class='form-control' />
                 
                </div>

                <div class="md-form mb-5">
                  <label for="billing_address2" class="">Address 2 (optional)</label>
                  <input type='text' placeholder='Apartment or suite' id='billing_address2' name='billing_address2' class='form-control' />
                 
                </div>

                <div class="row">
                  <div class="col-lg-4 col-md-12 mb-4">
                    <label for="country">Country</label>
                    {{ form.billing_country }}
                    <div class="invalid-feedback">
                      Please select a valid country.
                    </div>
                  </div>

                  <div class="col-lg-4 col-md-6 mb-4">
                    <label for="billing_zip">Zip</label>
                    <input type='text' placeholder='Zip code' id='billing_zip' name='billing_zip' class='form-control' />
                    <div class="invalid-feedback">
                      Zip code required.
                    </div>
                  </div>

                </div>

                <div class="custom-control custom-checkbox">
                  <input type="checkbox" class="custom-control-input" name="set_default_billing" id="set_default_billing">
                  <label class="custom-control-label" for="set_default_billing">Save as default billing address</label>
                </div>

              </div>

              {% if default_billing_address %}
              <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" name="use_default_billing" id="use_default_billing">
                <label class="custom-control-label" for="use_default_billing">Use default billing address: {{ default_billing_address.street_address|truncatechars:10 }}</label>
              </div>
              {% endif %}
              <hr>

              <h3>Payment option</h3>

              <div class="d-block my-3">
                {% for value, name in form.fields.payment_option.choices %}
                <div class="custom-control custom-radio">
                  <input id="{{ name }}" name="payment_option" value="{{ value }}" type="radio" class="custom-control-input" required>
                  <label class="custom-control-label" for="{{ name }}">{{ name }}</label>
                </div>
                {% endfor %}
              </div>

              <hr class="mb-4">
              <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>

            </form>

          </div>

        </div>

        <div class="col-md-4 mb-4">
          {% include "company/order_snippet.html" %}
        </div>

      </div>

    </div>
  </main>

{% endblock content %}

{% block extra_scripts %}
<script>
var hideable_shipping_form = $('.hideable_shipping_form');
var hideable_billing_form = $('.hideable_billing_form');

var use_default_shipping = document.querySelector("input[name=use_default_shipping]");
var use_default_billing = document.querySelector("input[name=use_default_billing]");

use_default_shipping.addEventListener('change', function() {
  if (this.checked) {
    hideable_shipping_form.hide();
  } else {
    hideable_shipping_form.show();
  }
})

use_default_billing.addEventListener('change', function() {
  if (this.checked) {
    hideable_billing_form.hide();
  } else {
    hideable_billing_form.show();
  }
})

</script>
{% endblock extra_scripts %}