b2bmart/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('help/', TemplateView.as_view(template_name="help.html"), name="help"),

    path('about-us/', TemplateView.as_view(template_name="company/about-us.html"), name="about_us"),
    path('about-management/', TemplateView.as_view(template_name="company/management.html"), name="about_management"),
    path('about-media-center/', TemplateView.as_view(template_name="company/media-center.html"), name="about_media_center"),
    path('about-work-with-us/', TemplateView.as_view(template_name="company/workWithUs.html"), name="about_work_with_us"),
    path('about-contact-us/', TemplateView.as_view(template_name="company/contact-us.html"), name="about_contact_us"),
    path('help-center/', TemplateView.as_view(template_name="company/help.html"), name="help_center"),
    path('privacy-policy/', TemplateView.as_view(template_name="company/privacy-policy.html"), name="privacy_policy"),
    path('trading-policy/', TemplateView.as_view(template_name="company/trading-policy.html"), name="trading_policy"),
    path('term-condition/', TemplateView.as_view(template_name="company/term-condition.html"), name="term_condition"),
    path('edit-profile/', TemplateView.as_view(template_name="company/seller/user.html.html"), name="edit_profile"),
    path('certificate/', TemplateView.as_view(template_name="company/certificate.html"), name="certificate"),
    path('media-center/', TemplateView.as_view(template_name="company/media-center.html"), name="media_center"),
    path('advertise/', TemplateView.as_view(template_name="company/advertise.html"), name="advertise"),

    path('order-track/', TemplateView.as_view(template_name="company/ordertrack.html"), name="order_track"),
    #path('cart/', TemplateView.as_view(template_name="company/cart.html"), name="cart"),

    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('accounts/', include('allauth.urls')),
    path('', include("product.urls", namespace="product")),
    path('dashboard/', include('dashboard.urls', namespace="dashboard")),

    

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dashboard/urls.py
from django.urls import path
from . import views
app_name = "dashboard"

urlpatterns = [
    path('seller-dashboard/',views.SellerDashboardView.as_view(), name="seller_dashboard"),
    path('seller/contact-profile/',views.SellerContactProfileView.as_view(), name="seller_contact_profile"),
    path('seller/business-profile/',views.SellerBusinessProfileView, name="seller_business_profile"),
    path('seller/statutory/',views.SellerStatutoryView.as_view(), name="seller_statutory"),
    path('seller/bank/',views.SellerBankView.as_view(), name="seller_bank"),
    
    
    
    path('seller/add-product/',views.SellerAddProductView.as_view(), name="seller_add_product"),
    path('seller/manage-product/',views.SellerManageProductView, name="seller_manage_product"),
    path('seller/rearrange-product/',views.SellerReArrangeProductView.as_view(), name="seller_rearrange_product"),
    path('seller/bulk-price-update/<str:pk>',views.SellerBulkPriceUpdateView, name="seller_bulk_price_update"),
    path('seller/single-product-update/<str:pk>', views.SellerSingleProductUpdateView, name="seller_single_product_update"),
    path('<int:pk>/delete_product/', views.sellerDeleteProduct, name="seller_delete_product"),
    path('seller/category-report/',views.SellerCategoryReportView.as_view(), name="seller_category_report"),
    path('seller/analytics/',views.SellerAnalyticView.as_view(), name="seller_analytics"),
    

    path('seller/business-outlook/',views.SellerBusinessOutlookView.as_view(), name="seller_business_outlook"),
    path('seller/finance/',views.SellerFinancecView.as_view(), name="seller_finance"),
    path('seller/history/',views.SellerHistoryView.as_view(), name="seller_history"),
    path('seller/document/',views.SellerPhotoDocumentView.as_view(), name="seller_document"),
    path('seller/membership/',views.SellerMembershipView.as_view(), name="seller_membership"),
    path('seller/my-enquiry/',views.SellerMyEnquiryView.as_view(), name="seller_my_enquiry"),
    path('seller/settings/',views.SellerSettingsView.as_view(), name="seller_settings"),

    path('seller/social-share/',views.SellerSocialShareView.as_view(), name="seller_social_share"),
    path('seller/paid-service/',views.SellerPaidServiceView.as_view(), name="seller_paid_service"),
    path('seller/management/',views.SellerManagementView.as_view(), name="seller_management"),
    path('seller/media-center/',views.SellerMediaCenterView.as_view(), name="seller_media_center"),

    path('seller/company/<str:user>/',views.SellerCompanyView.as_view(), name="seller_company"),
    path('seller/product-detail/<int:pk>/',views.SellerProductDetailView.as_view(), name="seller_product_detail"),

    path('seller/arrange-product/<int:pk>/',views.SellerArangeProductView.as_view(), name="seller_arrange_product"),
    path('seller/unarrange-product/<int:pk>/',views.SellerUnArangeProductView.as_view(), name="seller_unarrange_product"),

    path('seller/add-home-product/<int:pk>/',views.SellerAddHomeView.as_view(), name="seller_add_home_product"),
    path('seller/remove-home-product/<int:pk>/',views.SellerRemoveHomeView.as_view(), name="seller_remove_home_product"),

    path('seller/companey-add/',views.SellersCompanyView, name="seller_company_add"),


    ####################################### Buyer #####################################
    path('buyer-dashboard/',views.BuyerDashboardView.as_view(), name="buyer_dashboard"),
    path('buyer-profile/',views.BuyerProfileView.as_view(), name="buyer_profile"),
    path('buyer-order/',views.BuyerOrderView.as_view(), name="buyer_order"),
    path('buyer-message/',views.BuyerMessageView.as_view(), name="buyer_message"),
    path('buyer-offer-request-detail/',views.BuyerOfferRequestDetailsView.as_view(), name="buyer_offer_request_detail"),
    path('buyer-enquiry/',views.BuyerEnquiryView.as_view(), name="buyer_enquiry"),
    path('buyer-recent-activity/',views.BuyerRecentActivityView.as_view(), name="buyer_recent_activity"),
    path('buyer-favourite/',views.BuyerFavouriteView.as_view(), name="buyer_favourite"),
    path('buyer-downloads/',views.BuyerDownloadsView.as_view(), name="buyer_downloads"),
    path('buyer-share/',views.BuyerShareView.as_view(), name="buyer_share"),

    path('share-detail/<str:slug>/',views.ShareDetailView.as_view(), name="share_detail"),
    path('category/', views.category, name="category"),


    path('add-to-cart/<pk>/', views.add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<pk>/', views.remove_from_cart, name='remove-from-cart'),
    path('remove-product-from-cart/<pk>/', views.remove_single_product_from_cart, name='remove-single-product-from-cart'),
    path('cart/', views.CartView.as_view(), name='cart'),


    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('add-coupon/', views.AddCouponView.as_view(), name='add-coupon'),


]

product/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name="product"

urlpatterns = [
    path("",views.HomeView, name="home_list"),
    path("category/",views.category, name="category"),
    # path(r'^homescroll/$',views.homescroll, name="homescroll"),
    path("<str:slug>/",views.WebsiteHomeList.as_view(), name="website_home_list")
]

dashboard/views.py
from django.shortcuts import render, redirect
import random
import string
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import View, ListView, DetailView
from django.views.generic.detail import DetailView
from accounts.models import Account
from django.contrib.auth.models import User
from django.forms import inlineformset_factory
from django.contrib import messages
from product.models import Product
from .models import SellerProfile, Account, SellerStatutory, SellerBank, BusinessProfile, SellerCompany
from accounts.views import is_seller, is_buyer
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from django.contrib import messages
from .forms import *
from django.utils import timezone
from product.forms import ProductForm
from product.models import *
from accounts.models import ProfilePicture
from django.http import HttpResponseRedirect

class SellerDashboardView(LoginRequiredMixin, UserPassesTestMixin, View):
    def test_func(self):
        return is_seller(self.request.user)

    def get(self,request, *args, **kwargs):
        return render(request, 'dashboard/seller/dashboard.html')

class SellerContactProfileView(LoginRequiredMixin, UserPassesTestMixin, View):
    def test_func(self):
        return is_seller(self.request.user)

    def post(self,request, *args, **kwargs):
        first_name =request.POST['first_name']
        last_name =request.POST['last_name']
        promoter_first_name =request.POST['promoter_first_name']
        promoter_last_name =request.POST['promoter_last_name']
        company =request.POST['company']
        designation =request.POST['designation']
        address_building =request.POST['address_building']
        address_area =request.POST['address_area']
        landmark =request.POST['landmark']
        locality =request.POST['locality']
        city =request.POST['city']
        state =request.POST['state']
        country =request.POST['country']
        pincode =request.POST['pincode']
        gstin =request.POST['gstin']
        company_website =request.POST['company_website']
        mobile =request.POST['mobile']
        alternative_mobile =request.POST['alternative_mobile']
        email =request.POST['email']
        alternative_email =request.POST['alternative_email']
        landline_no =request.POST['landline_no']
        alternative_landline_no =request.POST['alternative_landline_no']
        about_me =request.POST['about_me']
        user = User.objects.get(username=request.user.username)
        user.first_name = first_name
        user.last_name = last_name
        user.save()

        account = Account.objects.get(user=request.user)
        account.mobile = mobile
        account.state = state
        account.pincode = pincode
        account.company_name = company
        account.save()
        try:
            seller = SellerProfile.objects.filter(user=request.user)[0]
            if seller:
                seller.user = request.user
                seller.promoter_first_name = promoter_first_name
                seller.promoter_last_name = promoter_last_name
                seller.designation = designation
                seller.address_building = address_building
                seller.address_area = address_area
                seller.landmark = landmark
                seller.city = city
                seller.country = country
                seller.gstin = gstin
                seller.company_website = company_website
                seller.alternative_mobile = alternative_mobile
                seller.alternative_email = alternative_email
                seller.landline_no = landline_no
                seller.alternative_landline_no = alternative_landline_no
                seller.about_me = about_me
                seller.save()
                return redirect(".")
        except:
            seller = SellerProfile(user=request.user, promoter_first_name=promoter_first_name,
                promoter_last_name=promoter_last_name, designation=designation, address_building=address_building,
                address_area=address_area, 
                landmark=landmark, locality=locality, city=city,country=country,
                gstin=gstin, company_website=company_website, alternative_mobile=alternative_mobile,
                alternative_email=alternative_email, landline_no=landline_no, 
                alternative_landline_no=alternative_landline_no, about_me=about_me)
            seller.save()
            return redirect(".")

    def get(self,request, *args, **kwargs):

        account = Account.objects.get(user=request.user)
        try:
            seller = SellerProfile.objects.get(user=request.user)
            context = {'account': account,
                    'seller': seller
                    }
        except:
            context = {'account': account
                    }
        return render(request, 'dashboard/seller/contact_profile.html', context)

class SellerStatutoryView(LoginRequiredMixin, UserPassesTestMixin, View):
    def test_func(self):
        return is_seller
    def post(self,request, *args, **kwargs):
            try:
                statutory = SellerStatutory.objects.get(user=request.user)
                if statutory:
                    statutory.gst_no = request.POST['gst_no']
                    statutory.pan_no = request.POST['pan_no']
                    statutory.tan_no = request.POST['tan_no']
                    statutory.cin_no = request.POST['cin_no']
                    statutory.dgft_ie_code = request.POST['dgft_ie_code']
                    statutory.company_registration_no = request.POST['company_registration_no']
                    statutory.save()
            except:
                gst_no = request.POST['gst_no']
                pan_no = request.POST['pan_no']
                tan_no = request.POST['tan_no']
                cin_no = request.POST['cin_no']
                dgft_ie_code = request.POST['dgft_ie_code']
                company_registration_no = request.POST['company_registration_no']
                statutory = SellerStatutory(user=request.user, gst_no=gst_no,
                            pan_no=pan_no,tan_no=tan_no, cin_no=cin_no,
                            dgft_ie_code=dgft_ie_code,company_registration_no=company_registration_no)
                statutory.save()
                return redirect(".")
                
            return redirect(".")  

    def get(self,request, *args, **kwargs):
        try:
            statutory = SellerStatutory.objects.get(user=request.user)
            context = { 'statutory':statutory}
        except:
            context=None
        return render(request, 'dashboard/seller/statutory.html', context)


@login_required
def SellerBusinessProfileView(request):
    #seller = BusinessProfile.objects.get(user=request.user)
    seller = request.user.businessprofile
    form = BusinessProfileForm(instance= seller)

    if request.method == 'POST':
        form = BusinessProfileForm(request.POST, request.FILES, instance=seller)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your profile was updated successfully')
    try:
        sellers = SellerProfile.objects.get(user=request.user)
        context = {'form':form, 'seller': seller,'sellers':sellers }
    except:
        context = {'form':form, 'seller': seller,}
    return render(request, 'dashboard/seller/business_profile.html', context)

class SellerBankView(LoginRequiredMixin, UserPassesTestMixin, View):
    def test_func(self):
        return is_seller(self.request.user)
    
    def post(self,request, *args, **kwargs):
        form = SellerBankForm(request.POST)
        if form.is_valid:
            try:
                dilip = form.save(commit=False)
                dilip.user = request.user
                dilip.save()
                return redirect(".")
            except:
                seller_bank = SellerBank.objects.get(user=request.user)
                seller_bank.bank_name = form.cleaned_data['bank_name']
                seller_bank.account_no = form.cleaned_data['account_no']
                seller_bank.bank_account_name = form.cleaned_data['bank_account_name']
                seller_bank.ifsc_code = form.cleaned_data['ifsc_code']
                seller_bank.account_type = form.cleaned_data['account_type']

                seller_bank.alternative_bank_name = form.cleaned_data['alternative_bank_name']
                seller_bank.alternative_account_no = form.cleaned_data['alternative_account_no']
                seller_bank.alternative_bank_account_name = form.cleaned_data['alternative_bank_account_name']
                seller_bank.alternative_bank_ifsc_code = form.cleaned_data['alternative_bank_ifsc_code']
                seller_bank.alternative_bank_account_type = form.cleaned_data['alternative_bank_account_type']
                seller_bank.save()
                return redirect(".")                    

    def get(self,request, *args, **kwargs):
        try:
            seller_bank = SellerBank.objects.get(user=request.user)
            context= {'seller_bank':seller_bank}
        except:
            context = None
        return render(request, 'dashboard/seller/bank_details.html', context)

class SellerSocialShareView(LoginRequiredMixin,UserPassesTestMixin, View):
    def test_func(self):
        return is_seller(self.request.user)
    def get(self, *args, **kwargs):
        return render(self.request, 'dashboard/seller/share.html')

class SellerAddProductView(LoginRequiredMixin, UserPassesTestMixin, View):
    def test_func(self):
        return is_seller(self.request.user)

    def post(self,request, *args, **kwargs):
        if request.method == "POST":  
            user = request.user                  

templates/dashboard/buyer/buyer_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <link rel="apple-touch-icon" sizes="76x76" href="{% static 'buyer/assets/img/apple-icon.png' %}">
  <link rel="icon" type="image/png" href="{% static 'buyer/assets/img/favicon.png' %}">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <title>
    Dashboard
  </title>
  <meta content='width=device-width, initial-scale=1.0, shrink-to-fit=no' name='viewport' />
  <!--     Fonts and icons     -->
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
  <!-- CSS Files -->
  <link href="{% static 'buyer/assets/css/material-dashboard.css' %}" rel="stylesheet" />
  <!-- CSS Just for demo purpose, don't include it in your project -->
  <link href="{% static 'buyer/assets/demo/demo.css' %}" rel="stylesheet" />
</head>

<body class="">
  <div class="wrapper ">
    <div class="sidebar" data-color="purple" data-background-color="white" data-image="{% static 'buyer/assets/img/sidebar-1.jpg' %}">
      <div class="logo position-relative">
        <a href="#" class="simple-text logo-normal">
          Company Logo
        </a>
      </div>
      <div class="sidebar-wrapper position-relative">
        <ul class="nav">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'dashboard:buyer_dashboard' %}">
              <i class="material-icons">dashboard</i>
              <p>Dashboard</p>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'dashboard:buyer_profile' %}">
              <i class="material-icons">account_circle</i>
              <p>My Account</p>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'dashboard:buyer_order' %}">
              <i class="material-icons">star_border</i>
              <p>My Order</p>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'dashboard:buyer_message' %}">
              <i class="material-icons">message</i>
              <p>Message</p>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'dashboard:buyer_offer_request_detail' %}">
              <i class="material-icons">local_offer</i>
              <p> Offer Request Details</p>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <i class="material-icons">grading</i>
              <p>My Enquies</p>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <i class="material-icons">local_activity</i>
              <p>My Recent Activity</p>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <i class="material-icons">favorite</i>
              <p>My Favourite</p>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'dashboard:buyer_downloads' %}">
              <i class="material-icons">cloud_download</i>
              <p>My Download</p>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'dashboard:buyer_share' %}">
              <i class="material-icons">share</i>
              <p>Share and Earn</p>
            </a>
          </li>
          <li class="nav-item home">
            <a class="nav-link" href="{% url 'product:home_list' %}">
              <i class="material-icons">home</i>
              <p>Home</p>
            </a>
          </li>
        </ul>
      </div>
    </div>
    
    {% block content %}
        
    {% endblock content %}
        
  </div>
  
  <!--   Core JS Files   -->
  <script src="{% static 'buyer/assets/js/core/jquery.min.js' %}"></script>
  <script src="{% static 'buyer/assets/js/core/popper.min.js' %}"></script>
  <script src="{% static 'buyer/assets/js/core/bootstrap-material-design.min.js' %}"></script>
  <script src="{% static 'buyer/assets/js/plugins/perfect-scrollbar.jquery.min.js' %}"></script>
  <!-- Plugin for the momentJs  -->
  <script src="{% static 'buyer/assets/js/plugins/moment.min.js' %}"></script>
  <!--  Plugin for Sweet Alert -->
  <script src="{% static 'buyer/assets/js/plugins/sweetalert2.js' %}"></script>
  <!-- Forms Validations Plugin -->
  <script src="{% static 'buyer/assets/js/plugins/jquery.validate.min.js' %}"></script>
  <!-- Plugin for the Wizard, full documentation here: https://github.com/VinceG/twitter-bootstrap-wizard -->
  <script src="{% static 'buyer/assets/js/plugins/jquery.bootstrap-wizard.js' %}"></script>
  <!--	Plugin for Select, full documentation here: http://silviomoreto.github.io/bootstrap-select -->
  <script src="{% static 'buyer/assets/js/plugins/bootstrap-selectpicker.js' %}"></script>
  <!--  Plugin for the DateTimePicker, full documentation here: https://eonasdan.github.io/bootstrap-datetimepicker/ -->
  <script src="{% static 'buyer/assets/js/plugins/bootstrap-datetimepicker.min.js' %}"></script>
  <!--  DataTables.net Plugin, full documentation here: https://datatables.net/  -->
  <script src="{% static 'buyer/assets/js/plugins/jquery.dataTables.min.js' %}"></script>
  <!--	Plugin for Tags, full documentation here: https://github.com/bootstrap-tagsinput/bootstrap-tagsinputs  -->
  <script src="{% static 'buyer/assets/js/plugins/bootstrap-tagsinput.js' %}"></script>
  <!-- Plugin for Fileupload, full documentation here: http://www.jasny.net/bootstrap/javascript/#fileinput -->
  <script src="{% static 'buyer/assets/js/plugins/jasny-bootstrap.min.js' %}"></script>
  <!--  Full Calendar Plugin, full documentation here: https://github.com/fullcalendar/fullcalendar    -->
  <script src="{% static 'buyer/assets/js/plugins/fullcalendar.min.js' %}"></script>
  <!-- Vector Map plugin, full documentation here: http://jvectormap.com/documentation/ -->
  <script src="{% static 'buyer/assets/js/plugins/jquery-jvectormap.js' %}"></script>
  <!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
  <script src="{% static 'buyer/assets/js/plugins/nouislider.min.js' %}"></script>
  <!-- Include a polyfill for ES6 Promises (optional) for IE11, UC Browser and Android browser support SweetAlert -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/core-js/2.4.1/core.js' %}"></script>
  <!-- Library for adding dinamically elements -->
  <script src="{% static 'buyer/assets/js/plugins/arrive.min.js' %}"></script>
  <!--  Google Maps Plugin    -->
  <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
  <!-- Chartist JS -->
  <script src="{% static 'buyer/assets/js/plugins/chartist.min.js' %}"></script>
  <!--  Notifications Plugin    -->
  <script src="{% static 'buyer/assets/js/plugins/bootstrap-notify.js' %}"></script>
  <!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="{% static 'buyer/assets/js/material-dashboard.js?v=2.1.2" type="text/javascript"></script>
  <!-- Material Dashboard DEMO methods, don't include it in your project! -->
  <script src="{% static 'buyer/assets/demo/demo.js' %}"></script>
  
  <script>
    $(document).ready(function() {
      // Javascript method's body can be found in assets/js/demos.js
      md.initDashboardPageCharts();

    });
  </script>
</body>

</html>